### ISSUE TITLE
Pet Charms >1000 don't show the 1000 stack in the inventory count

### ISSUE THREAD

**Issue by ThiefMaster** [eldir/Altoholic#1]
I have one stack of 1000 Pet Charms and another smaller stack. The tooltip with the amount of items I have only shows the smaller stack, ~~~regardless of where I have the items~~~.

Note: I encountered this with the original Altoholic. But looking at the commits I don't think this is fixed here (unless it's something generic )

Original Curseforge issue: https://wow.curseforge.com/projects/altoholic/issues/1007

**Comment by eldir** [comment]
![63c83d498ac4da6fc0b8eb31e3ba9711](https://user-images.githubusercontent.com/5166778/38779975-ea5195c8-40c7-11e8-8c06-d8ba9f16243d.png)
Do you have another addon that could be messing with this because it seems to work for me?

**Comment by eldir** [comment]
Where exactly do you have them? Does it pick them up if you move them all into your bags / backpack?

**Comment by ThiefMaster** [comment]
Same problem with git master.

It looks like the main bank area is completely ignored:
![image](https://user-images.githubusercontent.com/179599/38780116-37c9e990-40d2-11e8-9ace-15cef2f4f222.png)

If I move it to a different bag in my bank it works fine.

---

BTW, it would be nice if you could put your fork on Curse as well to get auto-updates. Having to keep a local git clone or download ZIP files all the time isn't very convenient.

**Comment by eldir** [comment]
Use the development branch. Yeah, I've tried to get a hold of the original author, I don't want to infringe on his work... just fixing some stuff for my own convenience. I've tried contacting him, but so far no luck.

**Comment by ThiefMaster** [comment]
Same problem in dev (but I wasn't running Twitch/Curse anyway).

**Comment by eldir** [comment]
@ThiefMaster try the latest dev build, I think that should fix it. You'll have to open and close the bank on all alts for it to fully update.

**Comment by eldir** [comment]
In hindsight this might not work for players who do not have the bag extension given by using two-factor authentication. I will ask a friend who does not have it to try it out as well.

**Comment by ThiefMaster** [comment]
Works fine, thanks!

**Comment by eldir** [comment]
Great, thanks for the feedback. Closing the issue then.
